export const FINANCE_SELECT_OPTIONS = {
  status: ["D", "P", "C"],
  ship_type: [
    "dry_bulk",
    "tankers",
    "container",
    "specialized_cargo",
    "passenger_vehicle_ferries",
    "offshore_support",
    "other_specialized",
    "superyachts_leisure",
  ],
  financing_product_type: [
    "debt_financing",
    "pre_delivery_loan",
    "post_delivery_loan",
    "ship_mortgage_loan",
    "senior_secured_loan",
    "mezzanine",
    "working_capital_loan",
    "bridge_loan",
    "sale_leaseback",
    "finance_lease",
    "time_charter_backed_loan",
    "voyage_charter_financing",
    "bareboat_charter_financing",
    "operating_lease",
    "private_equity_vc_funding",
    "joint_ventures",
    "public_equity",
    "convertible_bonds",
    "ship_bonds",
    "securitization_abs",
    "eca_backed_loan",
    "distressed_asset_financing",
    "green_ship_financing",
    "sharia_compliant",
    "tokenized_asset_financing",
    "shipbuilding_subsidies",
    "scrapping_incentives",
    "maritime_guarantee_schemes",
  ],
  project_financed_type: ["new_built", "second_hand_sp", "charter_backed", "alternative"],
  amortization_profile: ["standard", "bullet", "balloon"],
  required_service: ["equity", "financing", "sp", "workouts", "evaluations", "general_advisory"],
  financing_rate_type: ["floating_rate", "fixed_rate", "eca_backed_loan_rate"],
  derivative_hedging_type: ["irs", "caps", "floor", "collars"],
  transaction_stage: [
    "pre_transaction",
    "due_diligence_negotiation",
    "contracting_closing",
    "post_transaction",
    "contingency_dispute",
    "other",
  ],
  collateral_type: ["vessel_value", "charter_contracts", "corporate_guarantee_assets"],
  ltv_ratio_bucket: ["p5_10", "p10_25", "p25_50", "p50_70", "p70_90", "other"],
  tenor_bucket: ["m6_12", "y1_3", "y2_5", "y3_7", "y5_12", "y8_15"],
} as const;

export const FINANCE_FIELD_LABELS: Partial<Record<keyof typeof FINANCE_SELECT_OPTIONS, string>> = {
  status: "Status",
  ship_type: "Ship Type",
  financing_product_type: "Financing Product Type",
  project_financed_type: "Project Financed Type",
  amortization_profile: "Amortization Profile",
  required_service: "Required Service",
  financing_rate_type: "Financing Rate Type",
  derivative_hedging_type: "Derivative Hedging Type",
  transaction_stage: "Transaction Stage",
  collateral_type: "Collateral Type",
  ltv_ratio_bucket: "LTV Ratio Bucket",
  tenor_bucket: "Tenor Bucket",
};

export const toOptionLabel = (value: string) =>
  value
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
